### ISSUE TITLE
Empty data in html report

### ISSUE THREAD

**Issue by dbykadorov** [Halleck45/PhpMetrics#130]
PHPMetrics version v1.4.1 (phar)

Command: `phpmetrics --report-html=phpmetrics.html --report-cli --chart-bubbles=chart.svg apps`

Cli report and bubbles chart seems working fine, but html report doesn't have any charts but have a JS error because `data` and `groupedData` have no values:

```javascript
    ...
    var rAxis = 'loc';

    var data = 
    var groupedData = 

    var ruleSet = ...
```

Screen: http://joxi.ru/823j4zdFjGVlmO

~~What I'm doing wrong?~~

UPD: Seems like this issue related for the project only. Other project has been analyzed successfully. How I can dedug this issue? -vvv or --verbose provides the same output as normal run.

**Comment by Halleck45** [comment]
Hi,

can you test with the latest PhpMetrics version please ?

Debug JS is not so easy in phpMetrics, you shoul inspect code with your browser console :/

**Comment by dbykadorov** [comment]
Looks like it working now even for "bad" project, thank you!

![image](https://cloud.githubusercontent.com/assets/243108/9405190/65f15bfc-47fe-11e5-97e9-4523b3a5b923.png)

**Comment by Halleck45** [comment]
Cool :)

I close this issue

**Comment by bbonnesoeur** [comment]
Hello, I have a same related issue with the composer installation version 1.8.

with the command `phpmetrics --report-html=myreport.html --report-cli` in the HTML report the SVG graph don't display  it seems here is some js problem.

![phpmetrics](https://cloud.githubusercontent.com/assets/5261409/13462149/279da5a6-e086-11e5-8d96-63e38847b640.png)

any idea or starting point to look at ?

thanks !

PS : At first time it didn't work because graphiz dependency was not installed but without the --report-cli you can't be notified of it. Maybe an output without this option or some waring in the doc could be helpfull ?
