### ISSUE TITLE
Exception: Closure detected instead of method

### ISSUE THREAD

**Issue by andreimavenhut** [Halleck45/PhpMetrics#139]
[Exception]
  a 'Exception' exception occured analyzing file ./lib/Google/Service/Directory.php
  Message: Closure detected instead of method
  Details:
  ------------
  Stack:
  #0 phar:///usr/local/bin/phpmetrics/src/Hal/Component/OOP/Extractor/Extractor.php(128): Hal\Component\OOP\Extractor\MethodExtractor->extract(15160, Object(Hal\Component\Token\TokenCollection))
  #1 phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/Analyze/FileAnalyzer.php(138): Hal\Component\OOP\Extractor\Extractor->extract('./lib/Google/Se...')
  #2 phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/DoAnalyze.php(121): Hal\Application\Command\Job\Analyze\FileAnalyzer->execute('./lib/Google/Se...')
  #3 phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/Queue.php(51): Hal\Application\Command\Job\DoAnalyze->execute(Object(Hal\Component\Result\ResultCollection), Object(Hal\Component\Result\ResultCollection))
  #4 phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/RunMetricsCommand.php(119): Hal\Application\Command\Job\Queue->execute(Object(Hal\Component\Result\ResultCollection), Object(Hal\Component\Result\ResultCollection))
  #5 phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Hal\Application\Command\RunMetricsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutpu
  t))
  #6 phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #7 phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Hal\Application\Command\RunMetricsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Obje
  ct(Symfony\Component\Console\Output\ConsoleOutput))
  #8 phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #9 /usr/local/bin/phpmetrics(17): Symfony\Component\Console\Application->run()
  #10 {main}
  ------------

**Comment by rexem** [comment]
It seems that PhpMetrics cannot handle files bigger than 102 KB in a consistent way.

@andreimavenhut in your case, the only "quick and dirty fix" would be to set https://github.com/Halleck45/PhpMetrics/blob/master/src/Hal/Component/Token/Tokenizer.php#L30 to something bigger.


In order to avoid Memory allocation issues (see #13), the tokenizer is spiting large files in chunks. However, for example, if the split happens at the same time when T_STRING is defined the program will crash:
```
[...code...]
$x = "the 102400 bytes split happens here --> | <-- next chunk";
[...code...]
```

It doesn't look there's an easy solution for this. Without the 042f52f commit, the user could at least set memory limits manually if needed (still ugly), however right now it's not an option.

Not sure which solution @Halleck45 wants to go with, but it seems we're limited to:
- increase the 100 KB limit (not a "real" solution though)
- revert back to using raw token_get_all() for the full file (and/or allow user changing the memory/file limits)
- ignore large files completely
- use custom tokenizer (https://github.com/nikic/PHP-Parser ?)

I hope that helps.

**Comment by serbanghita** [comment]
This is because of a fix in https://github.com/Halleck45/PhpMetrics/issues/13

I believe that `Tokenizer::tokenize` should not attempt to split the file in chunks of `$limit` because this can result in random problems. Instead the user should be informed that if he runs `phpmetrics.phar` against big files, he should increase the `memory_limit` from `php.ini` in order for the tokenizer to work.

Since this is not a customer facing solution, reading large files and keeping large arrays in the memory is not an issue.

**Comment by serbanghita** [comment]
@Halleck45 any thoughts on this?

**Comment by Halleck45** [comment]
Hum, maybe ignoring big files is the solution. I'm not sure...

ping @UFOMelkor @fonsecas72

**Comment by fonsecas72** [comment]
I think that the best solution right now would be to ignore big files. Nevertheless I think we should give the user the possibility of setting this limit.

**Comment by UFOMelkor** [comment]
Ignoring big files and allowing to set a custom limit sounds IMHO like the best solution.

**Comment by Halleck45** [comment]
I don't see how calculate memory required by `token_get_all()` for a given file :(

For example: `memory = I_DONT_KNOW_WHAT * size_of_file()`

Do you have any idea ?

**Comment by Halleck45** [comment]
I made a benchmark: `token_get_all()` is a linear function.

I made a test with 100 files, from 1000 loc to 100000 loc. Memory consumed is linear (but not time). Each line of code cost around 4780 byte to be parsed by `token_get_all()` (excluding garbage collector)

I hope that [this commit](https://github.com/Halleck45/PhpMetrics/commit/1a65587fe8afdf2d426784b070032ad42836dee9) will resolve the problem definitively
