### ISSUE TITLE
Technical debt

### ISSUE THREAD

**Issue by xtrasmal** [Halleck45/PhpMetrics#143]
Is there a way to use the numbers PhpMetrics produces and calculate technical debt in hours?

**Comment by Halleck45** [comment]
Hum, I don't know... Maybe using Halstead's "time" and "efforts" metrics. But I don't know any formula to calculate technical debt

**Comment by rexem** [comment]
Hi @xtrasmal
Technical debt is a concept (not an empirical formula), and you would have to define your set of rules if you want to calculate it's value.
If you're referring to the technical debt as reported in packages like Sonar and similar - you'll see they have huge lists of rules (like "```use === instead of == -> penalty 1.5*Method_LOC minutes```"). 

I believe Sonar uses SQALE methodology, which unfortunately (at least currently) is out of PhpMetrics scope. [http://www.sqale.org/wp-content/uploads/2010/08/SQALE-Method-EN-V1-0.pdf]

However, since there are no concrete technical debt rules, and since they depend solely on your organization, you could always use any arbitrary formula that fits your needs, such as saying that to increase the Maintainability Index of your code by 1 point in a single file, will cost you e^(LOC) minutes, etc.

**Comment by xtrasmal** [comment]
Thanks. At work we run Sonar. I'll take a look at sqale.
